services:
  - type: web
    name: telegram-bot-klubnichka
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: TELEGRAM_TOKEN
        value: "8334802447:AAGD7H0akQpXgWRlh1xWaXsGmjV7DXJY8eM"
